// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1QSNm8yi_1i5U5D4uIDlzxiHRydBXpYQ',
    appId: '1:881289120957:web:4c9c2c90f2607ffc983bd4',
    messagingSenderId: '881289120957',
    projectId: 'bubble-5f5f3',
    authDomain: 'bubble-5f5f3.firebaseapp.com',
    storageBucket: 'bubble-5f5f3.appspot.com',
    measurementId: 'G-GDRK89YQWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-LB59ASmbY4JXtb7bgMklBxF7-KVlxs',
    appId: '1:881289120957:android:8298bcb12aa28b9c983bd4',
    messagingSenderId: '881289120957',
    projectId: 'bubble-5f5f3',
    storageBucket: 'bubble-5f5f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5g2RiqL4X2ld3UaPN1DlNx4Hd4rvQ8Xc',
    appId: '1:881289120957:ios:38cfe3548bb0ffc2983bd4',
    messagingSenderId: '881289120957',
    projectId: 'bubble-5f5f3',
    storageBucket: 'bubble-5f5f3.appspot.com',
    iosBundleId: 'com.example.bubble',
  );
}
